/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROCEDURE_H_RPCGEN
#define _PROCEDURE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define FILELENGTH 100

struct FileScanRes {
	int characters;
	int words;
	int lines;
	int errno;
};
typedef struct FileScanRes FileScanRes;

struct DirInput {
	int threshold;
	char *dir;
};
typedef struct DirInput DirInput;

#define PROCEDUREPROG 0x20000013
#define PROCEDUREVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILESCAN 1
extern  FileScanRes * filescan_1(char **, CLIENT *);
extern  FileScanRes * filescan_1_svc(char **, struct svc_req *);
#define DIRSCAN 2
extern  int * dirscan_1(DirInput *, CLIENT *);
extern  int * dirscan_1_svc(DirInput *, struct svc_req *);
extern int procedureprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILESCAN 1
extern  FileScanRes * filescan_1();
extern  FileScanRes * filescan_1_svc();
#define DIRSCAN 2
extern  int * dirscan_1();
extern  int * dirscan_1_svc();
extern int procedureprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_FileScanRes (XDR *, FileScanRes*);
extern  bool_t xdr_DirInput (XDR *, DirInput*);

#else /* K&R C */
extern bool_t xdr_FileScanRes ();
extern bool_t xdr_DirInput ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROCEDURE_H_RPCGEN */
