/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPCxFile.h"

bool_t
xdr_Giorno (XDR *xdrs, Giorno *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giorno, MAX_GIORNO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->previsione, MAX_PREVI,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->t_max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->t_min))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->file_audio, MAX_AUDIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response (XDR *xdrs, Response *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giorni, N,
		sizeof (Giorno), (xdrproc_t) xdr_Giorno))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Request (XDR *xdrs, Request *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giorno, MAX_GIORNO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->t_max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->t_min))
		 return FALSE;
	return TRUE;
}
