/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCXFILE_H_RPCGEN
#define _RPCXFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define N 7
#define MAX_GIORNO 10
#define MAX_PREVI 10
#define MAX_AUDIO 20

struct Giorno {
	char giorno[MAX_GIORNO];
	char previsione[MAX_PREVI];
	int t_max;
	int t_min;
	char file_audio[MAX_AUDIO];
};
typedef struct Giorno Giorno;

struct Response {
	Giorno giorni[N];
	int size;
};
typedef struct Response Response;

struct Request {
	char giorno[MAX_GIORNO];
	int t_max;
	int t_min;
};
typedef struct Request Request;

#define OPERATION 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define visualizza_dati 1
extern  Response * visualizza_dati_1(char **, CLIENT *);
extern  Response * visualizza_dati_1_svc(char **, struct svc_req *);
#define aggiorna_temperature 2
extern  int * aggiorna_temperature_1(Request *, CLIENT *);
extern  int * aggiorna_temperature_1_svc(Request *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define visualizza_dati 1
extern  Response * visualizza_dati_1();
extern  Response * visualizza_dati_1_svc();
#define aggiorna_temperature 2
extern  int * aggiorna_temperature_1();
extern  int * aggiorna_temperature_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Giorno (XDR *, Giorno*);
extern  bool_t xdr_Response (XDR *, Response*);
extern  bool_t xdr_Request (XDR *, Request*);

#else /* K&R C */
extern bool_t xdr_Giorno ();
extern bool_t xdr_Response ();
extern bool_t xdr_Request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCXFILE_H_RPCGEN */
