/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCXFILE_H_RPCGEN
#define _RPCXFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define N 10
#define DESC_LENGTH 31
#define TIPO_LENGTH 9
#define DATA_LENGTH 11
#define LUOGO_LENGTH 16

struct Inserimento {
	char descrizione[DESC_LENGTH];
	char tipo[TIPO_LENGTH];
	char date[DATA_LENGTH];
	char luogo[LUOGO_LENGTH];
	int disponibilita;
	int prezzo;
};
typedef struct Inserimento Inserimento;

struct Richiesta {
	char descrizione[DESC_LENGTH];
	int num_biglietti;
};
typedef struct Richiesta Richiesta;

#define OPERATION 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define inserimento_evento 1
extern  int * inserimento_evento_1(Inserimento *, CLIENT *);
extern  int * inserimento_evento_1_svc(Inserimento *, struct svc_req *);
#define acquista_biglietti 2
extern  int * acquista_biglietti_1(Richiesta *, CLIENT *);
extern  int * acquista_biglietti_1_svc(Richiesta *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define inserimento_evento 1
extern  int * inserimento_evento_1();
extern  int * inserimento_evento_1_svc();
#define acquista_biglietti 2
extern  int * acquista_biglietti_1();
extern  int * acquista_biglietti_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Inserimento (XDR *, Inserimento*);
extern  bool_t xdr_Richiesta (XDR *, Richiesta*);

#else /* K&R C */
extern bool_t xdr_Inserimento ();
extern bool_t xdr_Richiesta ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCXFILE_H_RPCGEN */
