/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPCxFile.h"

bool_t
xdr_Inserimento (XDR *xdrs, Inserimento *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->descrizione, DESC_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, TIPO_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->date, DATA_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->luogo, LUOGO_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->disponibilita))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prezzo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Richiesta (XDR *xdrs, Richiesta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->descrizione, DESC_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_biglietti))
		 return FALSE;
	return TRUE;
}
