/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPCxFile.h"

bool_t
xdr_Canzone (XDR *xdrs, Canzone *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cantante, MAX_CANTANTE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titolo, MAX_TITOLO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voti))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nomefile, MAX_FILE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response (XDR *xdrs, Response *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->canzoni, MAX_RESULT,
		sizeof (Canzone), (xdrproc_t) xdr_Canzone))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Request (XDR *xdrs, Request *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->isCantante))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cantante, MAX_CANTANTE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titolo, MAX_TITOLO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
